### ISSUE TITLE
Ensure timezone correctness

### ISSUE THREAD

**Issue by dacort** [dacort/metabase-athena-driver#31]
Currently, when queries are built, we'll use the `user.timezone` setting. This could lead to weirdness because timestamps in Athena are UTC.

For example, a simple query that tries to filter for a timestamp in the past 30 days results in a query that looks like this:

```sql
SELECT 
  "default"."mb_relative"."id" AS "id", "default"."mb_relative"."name" AS "name",
  "default"."mb_relative"."timestamp" AS "timestamp"
FROM "default"."mb_relative"
WHERE (
  "default"."mb_relative"."timestamp" >= timestamp '2020-01-01 00:00 America/Los_Angeles'
  AND "default"."mb_relative"."timestamp" < timestamp '2020-01-04 01:01 America/Los_Angeles'
) LIMIT 2000
```

Note that the time comparison uses the `America/Los_Angeles` timezone, which will lead to incorrect (or at best misleading) results.

I'm unsure of the right approach here - perhaps we hardcode `UTC` in the `unprepare/unprepare-value` functions? Or maybe something to do with `driver/db-default-timezone`?

**Comment by dacort** [comment]
I considered making this change in #28, but in the order of preserving existing behavior, I decided not too. This is a query generated in the older version - note the US/Pacific offset in the time (`08:00`).

```sql
SELECT
  "default"."mb_relative"."id" AS "id", "default"."mb_relative"."name" AS "name",
  "default"."mb_relative"."timestamp" AS "timestamp"
FROM "default"."mb_relative"
WHERE (
  "default"."mb_relative"."timestamp" >= from_iso8601_timestamp('2020-01-01T08:00:00.000Z')
  AND "default"."mb_relative"."timestamp" < from_iso8601_timestamp('2020-01-04T09:01:00.000Z')
) LIMIT 2000
```

**Comment by silberistgold** [comment]
Just ran into this issue. Do I understand correctly that

- Athena does not support saving `timestamp with timezone` but you are able to select a `timestamp` and convert it to a specific timezone using `at time zone 'Europe/Zurich'`?
- Metabase only displays timestamps in the selected report timezone if they have the type `timestamp with timezone` and simple `timestamp`s are always displayed in utc?
- The athena driver is able to use the metabase report timezone in the `where` part correctly?
- This is why the dates used in a metabase filter do not match the dates displayed on the results by metabase? (this is what you refer to as misleading because the filtering happens in the report timezone while the dates are displayed in utc)

If this is correct, I would suggest an option (or even make this the default behaviour) to use the report timezone for simple `timestamp`s in the `select` part as well. Then the displayed timestamp and the filtering should both happen in the report timezone as I would expect. From my point of view this does not apply to metabase in general but is a special case when using athena because of athenas missing support for `timestamp with timezone`.

Our current workaround for this is to "convert" all the dates to the timezone we want, then cutting of the timezone part and saving them as if they were utc dates when saving to athena. So metabase thinks all the dates (and the report timezone) are utc, when in fact they are in "Europe/Zurich". Here is an excerpt from the sql we use:

```
cast(
   from_iso8601_timestamp(substr(to_iso8601(from_iso8601_timestamp(item.createdat) at time zone 'Europe/Zurich'), 1, 23) || 'Z') as timestamp
) as createdat
```

Notice that the report timezone must be set to utc for this to work correctly.

**Comment by dacort** [comment]
Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). Any future issues can be asked about on their [forum](https://discourse.metabase.com/) or with a detailed [bug report](https://github.com/metabase/metabase/issues).
