### ISSUE TITLE
driver is error for cn regions 

### ISSUE THREAD

**Issue by hbuzhuhaoju** [dacort/metabase-athena-driver#70]
Dear Developer:
I used your latest Athena driver ,v1.10, but driver also throw exception for China region；

An error has been thrown from the AWS SDK client. Unable to execute HTTP request: athena.cn-north-1.amazonaws.com: Name or service not known [Execution ID not available]

Please forgive my bad english

**Comment by hbuzhuhaoju** [comment]
![image](https://user-images.githubusercontent.com/34302158/103125851-68770980-46c7-11eb-8133-2da1b2b57ccd.png)

**Comment by dacort** [comment]
@hbuzhuhaoju Sorry it didn't work for you. It should have in v1.1.0, but I'm glad you figured out how to get it work. 

I'm currently on vacation, but will try to double check this functionality when I'm back.

**Comment by dacort** [comment]
I think what may have happened here is that, by default, the Athena driver uses results set streaming, which *also* uses port `444` instead of port `443`. I'm guessing you weren't able to connect to port 444 and the connection timed out. That's why the EndpointOverride to port 443 worked. The driver *is* building the endpoint URL correctly. What I'm wondering is if result set streaming is available in cn region? But I think the Athena driver would take care of that automatically...

Debug logs:

```
Feb 17 16:30:14.399 DEBUG 56 com.simba.athena.athena.api.AJClient.AJClient: Building Athena Streaming client with endpoint = 'https://athena.cn-north-1.amazonaws.com:444' and region = 'cn-north-1'.
```
