### ISSUE TITLE
IAM Policy Changes - Athena

### ISSUE THREAD

**Issue by cabarria** [dacort/metabase-athena-driver#99]
I updated to the latest athena driver 1.3.1 running metabase 0.42.1 and noticed several new IAM policies needed and some that appear to have been deprecated by AWS.

These 3 policies were needed:
"athena:CreatePreparedStatement",
"athena:DeletePreparedStatement",
"athena:GetPreparedStatement"

These actions are no longer recognized:
CancelQueryExecution
GetCatalogs
GetExecutionEngine
GetExecutionEngines
GetNamespace
GetNamespaces
GetQueryExecutions
GetTable
GetTables
RunQuery

**Comment by jankatins** [comment]
Can confirm: I had to add the three actions to what is on https://github.com/dacort/metabase-athena-driver#example-iam-policy to at least save the new database in metabase.

**Comment by dacort** [comment]
Thanks @cabarria and @jankatins - it's interesting that you needed the `PreparedStaement` queries to save the database. I'll need to do a little work to verify this.

@cabarria I see similar deprecation notes, but not for all of the ones you mention:
```
athena:GetCatalogs
athena:GetExecutionEngine
athena:GetExecutionEngines
athena:GetNamespace
athena:GetNamespaces
athena:GetQueryExecutions
athena:GetTable
athena:GetTables
```

These are all likely due to when Athena used to use its own data catalog as opposed to Glue or when there was the v1 and v2 execution engines before v1 was deprecated. 

I don't see `CancelQueryExecution` and `RunQuery` in the current docs, but you're correct in that they're not supported either.
